### ISSUE TITLE
 checker doesn't work

### ISSUE THREAD

**Issue by jiajiala** [pavloDeshko/obsidian-index-checker#1]
Once one of my libraries has Advanced URI turned on by default, checker doesn't work

**Comment by jiajiala** [comment]
For some reason, seemingly unrelated to Advanced URI, it worked at first, and now it doesn't work with checker at all

**Comment by pavloDeshko** [comment]
> For some reason, seemingly unrelated to Advanced URI, it worked at first, and now it doesn't work with checker at all

hi, @jiajiala 
looks all right for me on 1.4.12 win, and 1.4.3 android

Could you give any details?

Also make sure the strict mode/community plugins are on, index-checker is on, desired plugin options are correct (index filename pattern, way of output, index markings, startup check, etc)

**Comment by pavloDeshko** [comment]
> Once one of my libraries has Advanced URI turned on by default, checker doesn't work

also seems to work with this plugin being on 

though if i understand correctly Advanced URI 'links' are not actually links for obsidian (you can't see them in 'linked view', for instance) so index-checker won't pick them either, unfortunately

**Comment by jiajiala** [comment]
My main library does not work, but my other libraries can be used normally, the main library and other libraries are shared.obsidian

This is strange.

Shared.obsidian

All Settings are supposed to be the same, but the main library just can't checker

The picture keeps stopping on this screen
![image](https://github.com/pavloDeshko/obsidian-index-checker/assets/73203026/67b8d534-d008-4cb1-85fd-638eb2f54053)



And the rest of my library is fine
![image](https://github.com/pavloDeshko/obsidian-index-checker/assets/73203026/9f58e14e-5230-439a-9701-274b650bdffd)


Even my main library many times, check is completely unresponsive

**Comment by jiajiala** [comment]
![image](https://github.com/pavloDeshko/obsidian-index-checker/assets/73203026/b3527605-a9bb-4b5d-bbc2-e8ebf8d51f7c)
Here's the problem

md and canvas files with the same name

The plug-in fails to be loaded

Thus, the checker cannot be performed

**Comment by pavloDeshko** [comment]
@jiajiala sorry, i've been busy for the past week, will look into it

thanks for tracking down the problem

**Comment by pavloDeshko** [comment]
fixed it! you can update the plugin

thanks again for finding this bug, it would take ages to replicate the issue without your clue 

@jiajiala
