### ISSUE TITLE
Ability to use .canvas file as index file

### ISSUE THREAD

**Issue by jiajiala** [pavloDeshko/obsidian-index-checker#3]
Use folder notes plug-in to manage files

Because you put files in folders with the same name to manage them

So when you need to search, you can penetrate the next layer of folders and get the folder note

**Comment by pavloDeshko** [comment]
hi, if i understand correctly you're trying to use .canvas files as index files. 

Unfortunately, currently obsidian doesn't provide any api for .canvas files, ie we can't get the list of all links a .canvas file contains, so we can't check it as index. It's technically possibly only by analysing the text of .canvas file itself, but it might have performance issues and generally much more complex that current implementation.

i guess the only way to keep index in .canvas file is to add index .md file to canvas file via "add note"

**Comment by pavloDeshko** [comment]
but i'll see what could be done about it..

**Comment by jiajiala** [comment]
Now I find that canvas is not useful, not as good as EXcalidraw, no longer use canvas as an index file...

**Comment by pavloDeshko** [comment]
now canvas files can be used as index files as of 1.0.0
update if you need it, cheers :)
