### ISSUE TITLE
Unable to check folder comments

### ISSUE THREAD

**Issue by jiajiala** [pavloDeshko/obsidian-index-checker#6]
![image](https://github.com/user-attachments/assets/568820e5-0b7f-416d-9ec6-7b347654ffc8)
As shown, I created a folder structure like 123 and created 1234note
But using the plug-in check, only 4 is listed
And 23 was ignored
But there should be 2 in 1, 3 in 2, 4 in 3
Layer by layer down
None of the options in the current plug-in can achieve this effect

**Comment by pavloDeshko** [comment]
hi, it seems to work as expected

Plugin will check the presence of links to **_files_** (notes) only, cause you can't reference a folder itself in obsidian.

Also an Index file (named as a pattern specifies) must be present in a each folder you want to maintain index on the first place, so plugin knows it should check this folder at all.
![image](https://github.com/user-attachments/assets/073e4822-9740-4c5c-a5ff-4b0657eec38b) red are indexes for each folder, each should have a link to _note

**Comment by jiajiala** [comment]
![image](https://github.com/user-attachments/assets/0010d674-bfb0-4b44-b179-7d61556773c4)
As shown in the figure, I set up such a folder/file structure
But when I check, the red marks are the links I should get
But the documents 1, 2, 2a are empty
That is, if I just open 1, I have no way of knowing that there are 2 and 2a in his subordinate file, because I will never check that the link is missing

I hope we can check on them. Thank you

**Comment by pavloDeshko** [comment]
i'm afraid i can't replicate your bug, works as it should for me.
![image](https://github.com/user-attachments/assets/4d3f47e7-f2fa-4285-9369-07c9c0a74b8b)
 Are you sure you have options set correctly (like 'all nested' and 'added to index file'? 
![image](https://github.com/user-attachments/assets/cfc70dc1-b41e-41a8-b5c8-4d2d9b05cbd6)

**Comment by jiajiala** [comment]
Like this picture you have here
![image](https://github.com/user-attachments/assets/09c16876-bf45-4efd-a399-32e6ffd9361f)
The link that should be in 1 is 2
The link that should be in 2 is 3
The link in 3 should be 4
And the link that should be in 4 is note
So I can find 2 in 1, 3 in 2, and note in 4
Because my 1234 is also an important note, they need to be linked, but now only the note can be linked

**Comment by jiajiala** [comment]
If you can support such a way, it will make the plugin even better, now all my files with the same name as the folder can only be manually checked to see if the file is linked to a higher level

**Comment by pavloDeshko** [comment]
right, got you now. You're saying plugin should not ignore index files themselfes when they are nested. We can do that. Do you think it should be the case for -smart-nested only, or for -all-nested mode too?

**Comment by jiajiala** [comment]
I'm supposed to use only -smart-nested myself, but I think other people might want it to work in -all-nested

Thank you for supporting this usage, it is very kind of you

**Comment by pavloDeshko** [comment]
did it! For smart nested only. You can update the plugin. Thanks for your feedback
